// <auto-generated />
namespace iCantina.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class iCantina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iCantina));
        
        string IMigrationMetadata.Id
        {
            get { return "202406072031246_iCantina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
